image: node:10

stages:
  - build
  - test
  - deploy

cache:
  key: da-master-key
  paths:
    - node_modules/

before_script:
  - npm ci

build-dev:
  stage: build
  retry: 1
  except:
    - master
  script:
    - npm run ng build -- --configuration=dev --progress false --output-path=dist
  artifacts:
    paths:
      - dist/

build-pro:
  stage: build
  retry: 1
  only:
    - master
  script:
    - npm run ng build -- --prod --progress false --output-path=dist
  artifacts:
    paths:
      - dist/

lint:
  stage: test
  script:
    - npm run lint -- --force

.unit-test:
  stage: test
  allow_failure: true
  script:
    - npm test -- --progress false --single-run=true --watch=false

.codequality:
  stage: test
  allow_failure: true
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
      --env SOURCE_CODE="$PWD" \
      --volume "$PWD":/code \
      --volume /var/run/docker.sock:/var/run/docker.sock \
      "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths:
      - codeclimate.json

deploy-dev:
  stage: deploy
  retry: 1
  dependencies:
    - build-dev
  tags:
    - deploy-dev-frontend
  script:
    - cp -af dist/ /root/frontend-static/
  only:
    - develop
  environment:
    name: dev
    url: https://dev.frikiradar.com

deploy-prod:
  stage: deploy
  retry: 1
  dependencies:
    - build-pro
  tags:
    - deploy-frontend
  script:
    - cp -af dist/ /root/frontend-static/
  only:
    - master
  environment:
    name: pro
    url: https://frikiradar.com
